
name: "Nightly"
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  analyze_sources:
    name: "Do we need to build the application?"
    runs-on: ubuntu-latest

    outputs:
      # Export 'filter' step check result so next step can use it.
      run_build: ${{ steps.filter.outputs.run_build }}

    steps:
    - name: "WILL BUILD STEP BE RUN?"
      id: filter
      run: |
        found="true"
        echo "::set-output name=run_build::${found}"

  # ##################################

  # Build step.
  build:
    name: "Gradle builder"
    runs-on: ubuntu-latest

    # Will run only if analyze_sources determined it is needed.
    needs: analyze_sources
    if: needs.analyze_sources.outputs.run_build == 'true'

    steps:
    - name: "Checkout sources"
      uses: actions/checkout@v2

    - name: "Set up JDK"
      uses: actions/setup-java@v2
      with:
        java-version: 14
        distribution: 'adopt'

    # ##################################

    - name: "Generate base name"
      id: vars
      run: |
        echo "::set-output name=now::$(date +%Y%m%d)"
        echo "::set-output name=base_name::logisim-evolution_develop_$(date +%Y%m%d)"

    - name: "Build sources JAR"
      run: |
        chmod +x gradlew
        ./gradlew sourcesJar

    - name: 'Upload sources JAR'
      uses: actions/upload-artifact@v2
      with:
        path: build/libs/logisim-evolution_3.5.0-src.jar
        name: ${{ steps.vars.outputs.base_name }}-src.jar

    - name: "Build binary JAR"
      run: |
        chmod +x gradlew
        ./gradlew sourcesJar

    - name: 'Upload binary JAR'
      uses: actions/upload-artifact@v2
      with:
        path: build/libs/logisim-evolution_3.5.0.jar
        name: ${{ steps.vars.outputs.base_name }}.jar

    # ##################################

    - name: "Build DEB"
      run: |
       chmod +x gradlew
       ./gradlew createDeb -x checkstyleMain -x checkstyleTest

    - name: 'Upload *.deb'
      uses: actions/upload-artifact@v2
      with:
        path: build/dist/logisim-evolution_3.5.0-1_amd64.deb
        name: ${{ steps.vars.outputs.base_name }}_amd64.deb
