#
# Logisim-evolution nightly builder
#
# Cron driven Github Action that uses tools/syncTranslations.py tool to
# ensure project *.properties files are in sync with English ones.
#
# Marcin Orlowski

name: "*.properties"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  markdown_lint:
    name: "*.properties sync check"
    runs-on: ubuntu-latest

    steps:
    # https://github.com/marketplace/actions/checkout
    - name: "Checkout sources"
      uses: actions/checkout@v2

    # https://github.com/marketplace/actions/paths-changes-filter
    - name: "Look for changed files..."
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          docs:
            - '**/*.properties'

    # https://github.com/marketplace/actions/my-markdown-linter
    - name: "Running sync checker..."
      run: |
        cd tools
        if ! ./syncTranslations.py > /tmp/report.txt; then
          echo ""
          echo "Project *.properties files out of sync! You can update"
          echo "them by hand or use tools/syncTranslations.py with --write"
          echo "to do the job for you."
          echo ""
          echo "Check report:"
          echo ""
          cat /tmp/report.txt
          echo ""
          exit 1
        fi
