#
# Logisim-evolution nightly builder
# https://github.com/logisim-evolution/logisim-evolution
#
# Cron driven Github Action builder, intended to create nightly builds
# from Logisim-evolution's "develop" branch. It assumes to be invoked
# daily (once per 24 hrs) and skips building if there was no repo activity
# during last 24 hours.
#
# Marcin Orlowski
#

name: "Snap"
on:
  # The "pull_request" trigger is here for debugging purposes and
  # as work-around for having this worker not yet in main branch.
  # Keep it disabled once it's merged into main branch as we only
  # want "schedule" to be the trigger.
  # NOTE: remove `if` condition marked with `HACK` once merged.
  pull_request:
    branches: [ develop ]
#    types: [ closed ]

env:
  JDK_VERSION: 16
  JDK_DISTRO: 'temurin'

jobs:
  # Building for Linux.
  build_linux:
    name: 'Linux build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout test branch'
        uses: actions/checkout@v2
        with:
          ref: 'snap-packages-test-1'

      - name: 'Build SNAP'
        # https://github.com/snapcore/action-build
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: 'Upload *.snap'
        uses: actions/upload-artifact@v3
        if: success()
        with:
           path: ${{ steps.snapcraft.outputs.snap }}
           name: ${{ needs.git_check.outputs.base_name }}_amd64.snap

        # ###########################################################################################
